# Generated by Django 6.0.8 on 2026-09-28 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_is_admin_to_admin_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_admin",
        ),
    ]
