# Generated by Django 6.0.8 on 2026-09-29 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_profile_is_admin"),
        ("members", "0006_remove_member_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="member",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to="members.member",
            ),
        ),
    ]
