# Generated by Django 6.0.8 on 2026-09-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_backfill_catalogue"),
    ]

    operations = [
        migrations.CreateModel(
            name="PanelScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Panel scope",
                "verbose_name_plural": "Panel scopes",
                "ordering": ["id"],
                "permissions": (
                    ("members__view", "members: view"),
                    ("members__manage", "members: manage"),
                    ("members__owner", "members: owner"),
                    ("schedule__view", "schedule: view"),
                    ("schedule__manage", "schedule: manage"),
                    ("schedule__owner", "schedule: owner"),
                    ("songs__view", "songs: view"),
                    ("songs__manage", "songs: manage"),
                    ("songs__owner", "songs: owner"),
                    ("gallery__view", "gallery: view"),
                    ("gallery__manage", "gallery: manage"),
                    ("gallery__owner", "gallery: owner"),
                    ("events__view", "events: view"),
                    ("events__manage", "events: manage"),
                    ("events__owner", "events: owner"),
                    ("notices__view", "notices: view"),
                    ("notices__manage", "notices: manage"),
                    ("notices__owner", "notices: owner"),
                    ("reports_hymnal_history__view", "reports.hymnal_history: view"),
                    ("reports_hymnal_history__manage", "reports.hymnal_history: manage"),
                    ("reports_hymnal_history__owner", "reports.hymnal_history: owner"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
