# Generated by Django 6.0.8 on 2026-09-26 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_member_first_name_member_last_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="members/"),
        ),
        migrations.CreateModel(
            name="MemberChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("field", models.CharField(max_length=32)),
                ("old_value", models.TextField(null=True)),
                ("new_value", models.TextField(null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "editor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_log",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "member change log entry",
                "verbose_name_plural": "member change log",
                "ordering": ["-changed_at", "-id"],
            },
        ),
    ]
