# Generated by Django 6.0.8 on 2026-09-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_member_photo_memberchangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="birth_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="birth_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="birth_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("birth_day__isnull", True), ("birth_month__isnull", True)),
                    models.Q(("birth_day__isnull", False), ("birth_month__isnull", False)),
                    _connector="OR",
                ),
                name="member_birth_day_month_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("birth_day__isnull", True),
                    models.Q(("birth_day__gte", 1), ("birth_day__lte", 31)),
                    _connector="OR",
                ),
                name="member_birth_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("birth_month__isnull", True),
                    models.Q(("birth_month__gte", 1), ("birth_month__lte", 12)),
                    _connector="OR",
                ),
                name="member_birth_month_range",
            ),
        ),
    ]
