# Generated by Django 6.0.8 on 2026-09-28 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_split_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="birth_date",
        ),
    ]
