# Generated by Django 6.0.3 on 2026-03-12 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='ChordChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('tone', models.CharField(blank=True, max_length=3)),
                ('instrument', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chord_charts', to='songs.song')),
            ],
            options={
                'unique_together': {('song', 'tone', 'instrument')},
            },
        ),
    ]
