# Generated by Django 6.0.8 on 2026-10-01 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0007_remove_servicewindow_service_window_end_after_start_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("saved_at", models.DateTimeField()),
                ("last_reminder_slot", models.DateTimeField(blank=True, null=True)),
                (
                    "saved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "setlist",
                "verbose_name_plural": "setlists",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SetlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("tone", models.CharField(max_length=3)),
                (
                    "setlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="songs.setlist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="setlist_items",
                        to="songs.song",
                    ),
                ),
            ],
            options={
                "verbose_name": "setlist item",
                "verbose_name_plural": "setlist items",
                "ordering": ["setlist", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="setlist",
            constraint=models.UniqueConstraint(fields=("date",), name="setlist_date_unique"),
        ),
        migrations.AddConstraint(
            model_name="setlistitem",
            constraint=models.UniqueConstraint(
                fields=("setlist", "position"), name="setlist_item_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="setlistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1), ("position__lte", 10)),
                name="setlist_item_position_range",
            ),
        ),
    ]
