from collections.abc import Iterator, Mapping, Sequence
from datetime import datetime
from typing import IO, Protocol
from uuid import UUID

from features.gallery.domain.trash_rules import TrashedItemKind
from features.gallery.dtos.gallery_dtos import AlbumCreate, AlbumRecord, NewPhoto, PhotoView
from features.gallery.dtos.trash_dtos import (
    PurgedBatch,
    TrashedRoot,
    TrashEntryRow,
    TrashOutcome,
)


class AlbumRepository(Protocol):
    """Live album rows. Writes that break sibling-unique names raise ``DuplicateAlbumNameError``;
    every write sets ``updated_at``.

    ``parent_map(lock=True)`` and ``next_position`` lock rows, so callers run them inside a
    transaction.
    """

    def exists(self, album_id: int) -> bool: ...

    def get_record(self, album_id: int) -> AlbumRecord | None: ...

    def list_records(self) -> list[AlbumRecord]: ...

    def sibling_name_taken(
        self, name: str, parent_id: int | None, exclude_id: int | None
    ) -> bool: ...

    def parent_map(self, lock: bool) -> dict[int, int | None]: ...

    def next_position(self, parent_id: int | None) -> int: ...

    def create(self, album: AlbumCreate, position: int) -> int: ...

    def update(self, album_id: int, fields: Mapping[str, object]) -> None: ...

    def child_ids(self, parent_id: int | None) -> list[int]: ...

    def apply_order(self, ids: Sequence[int]) -> None: ...

    def has_photos(self, album_id: int) -> bool: ...

    def set_cover_name(self, album_id: int, name: str | None) -> None: ...

    def set_cover_name_if_absent(self, album_id: int, name: str) -> bool: ...

    def live_sibling_named(self, name: str, parent_id: int | None) -> int | None: ...

    def touch(self, ids: Sequence[int]) -> None: ...

    def touch_photos_of(self, album_id: int) -> None: ...


class GalleryRepository(Protocol):
    """Live photo rows. ``create_photo`` and ``move_photo`` lock the target album row to append,
    and raise ``AlbumNotFoundError`` when that album is gone or trashed."""

    def list_all_photos(self) -> list[PhotoView]: ...

    def list_photos_by_album(self, album_id: int) -> list[PhotoView]: ...

    def list_photos_changed_since(self, since: datetime) -> list[PhotoView]: ...

    def get_photo(self, photo_id: int) -> PhotoView | None: ...

    def create_photo(self, photo: NewPhoto) -> PhotoView: ...

    def update_photo(self, photo_id: int, fields: Mapping[str, object]) -> None: ...

    def move_photo(self, photo_id: int, album_id: int) -> None: ...

    def photo_ids(self, album_id: int) -> list[int]: ...

    def apply_order(self, ids: Sequence[int]) -> None: ...

    def photos_without_thumbnail(self) -> Iterator[tuple[int, int, str]]: ...

    def set_thumbnail(self, photo_id: int, name: str) -> None: ...


class GalleryFileStorage(Protocol):
    """Gallery files (originals, thumbnails, covers) under random names below ``gallery/``."""

    def save_original(self, album_id: int, extension: str, stream: IO[bytes]) -> str: ...

    def save_thumbnail(self, album_id: int, content: bytes) -> str: ...

    def save_cover(self, album_id: int, content: bytes) -> str: ...

    def open(self, name: str) -> IO[bytes]: ...

    def delete(self, name: str) -> None: ...

    def url(self, name: str) -> str: ...


class TrashRepository(Protocol):
    """Deletion batches and the trashed rows they hold (specs/014-gallery-trash-sync)."""

    def create_batch(self, kind: TrashedItemKind, root_id: int, actor_id: UUID | None) -> UUID: ...

    def trash_photo(self, photo_id: int, batch_id: UUID) -> bool: ...

    def trash_albums(self, album_ids: Sequence[int], batch_id: UUID) -> list[int]: ...

    def trash_photos_of_albums(self, album_ids: Sequence[int], batch_id: UUID) -> list[int]: ...

    def batch_rooted_at(self, kind: TrashedItemKind, root_id: int) -> TrashedRoot | None: ...

    def restore_batch(self, batch_id: UUID) -> TrashOutcome: ...

    def list_entries(self) -> list[TrashEntryRow]: ...

    def expired_batch_ids(self, before: datetime) -> list[UUID]: ...

    def purge_batch(self, batch_id: UUID) -> PurgedBatch: ...


class DeletionMarkRepository(Protocol):
    """Deleted ids the change feed reports; independent of the rows."""

    def upsert(self, kind: TrashedItemKind, ids: Sequence[int]) -> None: ...

    def remove(self, kind: TrashedItemKind, ids: Sequence[int]) -> None: ...

    def ids_since(self, kind: TrashedItemKind, since: datetime) -> list[int]: ...

    def expire(self, before: datetime) -> int: ...
