# Generated by Django 6.0.8 on 2026-09-29 13:42

import django.db.models.deletion
import features.gallery.models.gallery
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={
                "ordering": ["position", "id"],
                "verbose_name": "album",
                "verbose_name_plural": "albums",
            },
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={
                "ordering": ["position", "id"],
                "verbose_name": "photo",
                "verbose_name_plural": "photos",
            },
        ),
        migrations.AddField(
            model_name="album",
            name="cover_image",
            field=models.ImageField(
                blank=True, upload_to=features.gallery.models.gallery.cover_upload_path
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="album",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="gallery.album",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photo",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to=features.gallery.models.gallery.thumbnail_upload_path
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["parent", "position"], name="album_parent_position"),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["album", "position"], name="photo_album_position"),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "name"),
                name="unique_album_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name",),
                name="unique_root_album_name",
            ),
        ),
    ]
