# Generated by Django 6.0.8 on 2026-09-29 15:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_backfill_positions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryDeletionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "root_kind",
                    models.CharField(
                        choices=[("album", "album"), ("photo", "photo")], max_length=5
                    ),
                ),
                ("root_id", models.PositiveIntegerField()),
                ("deleted_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "gallery deletion batch",
                "verbose_name_plural": "gallery deletion batches",
                "ordering": ["-deleted_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="GalleryDeletionMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("album", "album"), ("photo", "photo")], max_length=5
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("deleted_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "gallery deletion mark",
                "verbose_name_plural": "gallery deletion marks",
                "ordering": ["deleted_at", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="album",
            name="unique_album_name_per_parent",
        ),
        migrations.RemoveConstraint(
            model_name="album",
            name="unique_root_album_name",
        ),
        migrations.AddField(
            model_name="album",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="updated_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="photo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="updated_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="photo",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="photos",
                to="gallery.album",
            ),
        ),
        migrations.AddField(
            model_name="gallerydeletionbatch",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="deletion_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="albums",
                to="gallery.gallerydeletionbatch",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="deletion_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="photos",
                to="gallery.gallerydeletionbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=["cover_image"],
                name="album_trashed_cover",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=["image"],
                name="photo_trashed_image",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=["thumbnail"],
                name="photo_trashed_thumbnail",
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False), ("deleted_at__isnull", True)),
                fields=("parent", "name"),
                name="unique_live_album_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True), ("deleted_at__isnull", True)),
                fields=("name",),
                name="unique_live_root_album_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="gallerydeletionmark",
            constraint=models.UniqueConstraint(
                fields=("kind", "object_id"), name="unique_gallery_deletion_mark"
            ),
        ),
        migrations.AddConstraint(
            model_name="gallerydeletionbatch",
            constraint=models.UniqueConstraint(
                fields=("root_kind", "root_id"), name="unique_gallery_deletion_batch_root"
            ),
        ),
    ]
