# Generated by Django 5.2.7 on 2026-02-28 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_alter_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
